### ISSUE TITLE
App crashes when tapping on share button

### ISSUE THREAD

**Issue by danpashin** [danpashin/twackup-rs#10]
Some users reporting about weird crash when tapping on share button for deb

https://github.com/danpashin/twackup-rs/blob/d4596b5f3cfbe4c9fd0bd41110ef634606296d35/twackup-gui/Twackup/Sources/ViewControllers/Package/Detail/DatabaseDetailVC.swift#L25-L31

Or for package list

https://github.com/danpashin/twackup-rs/blob/d4596b5f3cfbe4c9fd0bd41110ef634606296d35/twackup-gui/Twackup/Sources/ViewControllers/Package/List/LeavesListVC.swift#L27-L38

Should investigate more. No backtrace at this moment
![crash](https://user-images.githubusercontent.com/11134266/208314779-623188d2-4821-421c-a7e7-ddc5e67a44c9.png)

**Comment by CySxL** [comment]
same issue

**Comment by danpashin** [comment]
> same issue

Can you send the crashlog? It is located in Preferences app -> Privacy -> Analytics & Improvement -> Analytics Data -> Twackup with the latest date

**Comment by CySxL** [comment]
> > same issue
> 
> 
> 
> Can you send the crashlog? It is located in Preferences app -> Privacy -> Analytics & Improvement -> Analytics Data -> Twackup with the latest date

sure at all! Sorry I saw the issue is created by you so I think you already had it.

**Comment by CySxL** [comment]
https://pastebin.com/AX8eKj8s

**Comment by danpashin** [comment]
> > > same issue
> > 
> > 
> > Can you send the crashlog? It is located in Preferences app -> Privacy -> Analytics & Improvement -> Analytics Data -> Twackup with the latest date
> 
> sure at all! Sorry I saw the issue is created by you so I think you already had it.

Yup, I have Sentry but it doesn't show log for some reason...

**Comment by CySxL** [comment]
> > > > same issue
> 
> > > 
> 
> > > 
> 
> > > Can you send the crashlog? It is located in Preferences app -> Privacy -> Analytics & Improvement -> Analytics Data -> Twackup with the latest date
> 
> > 
> 
> > sure at all! Sorry I saw the issue is created by you so I think you already had it.
> 
> 
> 
> Yup, I have Sentry but it doesn't show log for some reason...


No worries, I'm happy to provide further help !

**Comment by danpashin** [comment]
So after a couple of researching hours it seems that crash is not related to Twackup itself but the system... investigating more.

**Comment by SethWiiPlaza** [comment]
I'm having this issue as well, everything went fine up until the sharing process. Here are my specs:

iPhone 11 
iOS 14.0.1 
uncOver Version: 8.0.2

Hope this can be fixed, this app seems like a way better alternative to that garbage IAmLazy tweak
