### ISSUE TITLE
Random location of Rebuilded files

### ISSUE THREAD

**Issue by CySxL** [danpashin/twackup-rs#15]
As title.

Sometimes the Rebuilded .debs are placed in `/var/mobile/Documents` and sometimes in `/var/mobile/Containers/Data/Application/ Twackup /Documents`

**Comment by danpashin** [comment]
In GUI? 'Cause cli version saves in `/var/mobile/Documents/Twackup`

**Comment by CySxL** [comment]
> In GUI? 'Cause cli version saves in `/var/mobile/Documents/Twackup`

Yeah in GUI version from Bigboss.

I got confused for that, do that's why there was a closed issue 😂

Found out that it's Twackup stores them randomly.

**Comment by CySxL** [comment]
video demonstration: https://streamable.com/8ekrj9

**Comment by CySxL** [comment]
still happens in 2.0.2
![image](https://user-images.githubusercontent.com/15531137/208941189-02e4c153-ffb8-4c65-a37e-f7a99c4b80b9.png)
