### ISSUE TITLE
Syncing file simultaneously

### ISSUE THREAD

**Issue by CySxL** [danpashin/twackup-rs#16]
While I delete the rebuilded .debs in Filza, Twackup still showing them in GUI.

Empty Filza path: ![image](https://user-images.githubusercontent.com/15531137/208705440-6587ba3c-3ca4-4633-ab35-7f6db54dcf45.png)

GUI still showing deleted items:
![image](https://user-images.githubusercontent.com/15531137/208705480-8cb1d387-b4b2-412c-a7e7-b4891a89be9c.png)

**Comment by danpashin** [comment]
Expected behavior actually. Debs should be located in Twackup docs dir, not in `/var/mobile`

**Comment by CySxL** [comment]
> Expected behavior actually. Debs should be located in Twackup docs dir, not in `/var/mobile`

Actually the screenshot is Twackup docs dir...

Btw why I have them in /var/mobile/Documents ?
